import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Title from '@/components/Title'
import Sites from '@/components/Sites'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'


export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Nav/>
      
      <Footer/>
    </>
  )
}
